# Generated by Django 3.1.7 on 2021-05-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='meetUrl',
        ),
        migrations.AlterField(
            model_name='classpost',
            name='post_title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='section',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
